name: hybrid_search
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python>=3.8
  
  # Core ML and Vector Search
  - faiss-cpu>=1.7.4
  - numpy>=1.21.0
  
  # Data Processing
  - pandas>=1.3.0
  
  # Development
  - pip
  
  # Pip-only packages
  - pip:
    - sentence-transformers>=2.2.2
    - datasets>=2.0.0
